export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER'



export const NEW_ERROR = 'NEW_ERROR'
export const RESET_ERROR = 'RESET_ERROR'



export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';


export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS';
export const RESET_FRIEND_SUCCESS = 'RESET_FRIEND_SUCCESS';

export const GET_ALL_FRIEND_SUCCESS = 'GET_ALL_FRIEND_SUCCESS';RESET_ALL_FRIEND_SUCCESS
export const RESET_ALL_FRIEND_SUCCESS = 'RESET_ALL_FRIEND_SUCCESS';

export const CHECK_IS_THIS_USER_IS_FRIEND_SUCCESS = 'CHECK_IS_THIS_USER_IS_FRIEND_SUCCESS';



export const POST_NEWS_SUCCESS = 'POST_NEWS_SUCCESS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const RESET_NEWS_SUCCESS = 'RESET_NEWS_SUCCESS';
export const GET_MORE_NEWS_SUCCESS = 'GET_MORE_NEWS_SUCCESS';



export const GET_GALLEREY_SUCCESS = 'GET_GALLEREY_SUCCESS';
export const RESET_GALLEREY_SUCCESS = 'RESET_GALLEREY_SUCCESS';
export const GET_ALL_GALLEREY_AMOUNT = 'GET_ALL_GALLEREY_AMOUNT';
export const RESET_ALL_GALLEREY_AMOUNT = 'RESET_ALL_GALLEREY_AMOUNT';
export const POST_GALLEREY_SUCCESS = 'POST_GALLEREY_SUCCESS';
